language: php

dist: trusty
sudo: false

matrix:
  include:
    - php: 5.3
      sudo: required
      dist: precise

php:
  - '5.3'
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly

install:
  - composer install --dev --no-interaction --optimize-autoloader

script:
  - php bin/phpspec run
