language: php

dist: trusty
sudo: false

matrix:
  include:
    - php: 5.3
      sudo: required
      dist: precise

  allow_failures:
    - php: hhvm

php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - hhvm # on Trusty only
  - nightly

install: composer install --no-interaction --optimize-autoloader
script: composer run tests
